# Generated by Django 5.1.7 on 2025-08-19 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('nhis_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='Ongoing medical conditions', null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('spouse_partner_name', models.CharField(blank=True, max_length=100)),
                ('spouse_partner_phone', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adult_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('nhis_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='Ongoing medical conditions', null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('program_of_study', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('hall', models.CharField(blank=True, max_length=50)),
                ('parent_guardian_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_guardian_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VisitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('nhis_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('allergies', models.TextField(blank=True, help_text='Known allergies', null=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='Ongoing medical conditions', null=True)),
                ('current_medications', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visiting_purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('host_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('host_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('expected_stay_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('local_accommodation', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
