# Generated by Django 5.1.7 on 2025-08-23 10:38

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_adultprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID for external API references and QR codes', unique=True)),
                ('card_type', models.CharField(choices=[('smart', 'Smart Health Card'), ('nhis', 'NHIS Card (Linked)'), ('hybrid', 'Smart Card with NHIS Link')], default='smart', max_length=10)),
                ('nhis_number', models.CharField(blank=True, db_index=True, help_text='NHIS card number for linking', max_length=20, null=True)),
                ('nhis_link_status', models.CharField(choices=[('not_linked', 'Not Linked to NHIS'), ('pending', 'NHIS Verification Pending'), ('verified', 'NHIS Verified and Linked'), ('failed', 'NHIS Verification Failed'), ('expired', 'NHIS Link Expired')], default='not_linked', max_length=15)),
                ('nhis_verified_at', models.DateTimeField(blank=True, help_text='When NHIS linking was last verified', null=True)),
                ('nhis_verification_attempts', models.PositiveIntegerField(default=0, help_text='Number of NHIS verification attempts')),
                ('nhis_last_sync', models.DateTimeField(blank=True, help_text='Last successful data sync with NHIS', null=True)),
                ('nhis_verification_data', models.JSONField(blank=True, help_text='Encrypted NHIS verification details', null=True)),
                ('card_number', models.CharField(editable=False, help_text='Human-readable card number (e.g. SMART-XXXX-XXXX)', max_length=32, unique=True)),
                ('nfc_uid', models.CharField(blank=True, help_text='If a physical NFC card exists, store its chip UID here', max_length=64, null=True)),
                ('pin_hash', models.CharField(blank=True, help_text='Hashed PIN (optional, for in-person verification)', max_length=128, null=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr/health_cards/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('pending', 'Pending NHIS Verification')], default='active', max_length=20)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2028, 8, 22, 10, 38, 9, 552089, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_card', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['nhis_number', 'nhis_link_status'], name='api_healthc_nhis_nu_10fe48_idx'), models.Index(fields=['external_id'], name='api_healthc_externa_97836f_idx'), models.Index(fields=['card_number'], name='api_healthc_card_nu_8337f0_idx')],
            },
        ),
    ]
