# Generated by Django 5.1.7 on 2025-08-29 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_healthcard_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 8, 28, 0, 26, 53, 207854, tzinfo=datetime.timezone.utc)),
        ),
    ]
