# Generated by Django 5.1.7 on 2025-08-29 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_healthcard_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('clinic', 'Clinic'), ('pharmacy', 'Pharmacy')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_partner', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 8, 28, 2, 7, 16, 894500, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('adult', 'Adult'), ('visitor', 'Visitor'), ('doctor', 'Doctor')], default='student', max_length=50),
        ),
    ]
