# Generated by Django 5.1.7 on 2025-08-29 02:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_facility_alter_healthcard_expires_at_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 8, 28, 2, 11, 46, 40523, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facilities', models.ManyToManyField(blank=True, related_name='doctors', to='api.facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
