# Generated by Django 5.1.7 on 2025-08-29 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_healthcard_expires_at_doctorprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='facilities',
            new_name='clinics',
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 8, 28, 2, 13, 49, 888170, tzinfo=datetime.timezone.utc)),
        ),
    ]
