# Generated by Django 5.1.7 on 2025-08-29 02:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_facilities_doctorprofile_clinics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='admin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 8, 28, 2, 35, 0, 804458, tzinfo=datetime.timezone.utc)),
        ),
    ]
