# Generated by Django 5.1.7 on 2025-08-29 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_facility_admin_alter_healthcard_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 8, 28, 2, 37, 45, 208020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('facility_admin', 'Facility Admin'), ('student', 'Student'), ('adult', 'Adult'), ('visitor', 'Visitor'), ('doctor', 'Doctor')], default='student', max_length=50),
        ),
    ]
