# Generated by Django 5.1.7 on 2025-08-29 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_healthcard_expires_at_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 8, 28, 8, 13, 12, 775119, tzinfo=datetime.timezone.utc)),
        ),
    ]
