# Generated by Django 5.1.7 on 2025-08-29 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_healthcard_expires_at_appointment_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 8, 28, 15, 20, 21, 588956, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('suspended', 'Suspended'), ('on_leave', 'On Leave'), ('pending', 'Pending')], default='active', max_length=50),
        ),
    ]
