# Generated by Django 5.1.7 on 2025-08-29 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_healthcard_expires_at_alter_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 8, 28, 15, 25, 18, 367922, tzinfo=datetime.timezone.utc)),
        ),
    ]
