# Generated by Django 5.1.7 on 2025-09-14 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_healthcard_expires_at_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 9, 13, 23, 59, 48, 66714, tzinfo=datetime.timezone.utc)),
        ),
    ]
