# Generated by Django 5.1.7 on 2025-09-15 13:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_doctorprofile_latitude_doctorprofile_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2028, 9, 14, 13, 30, 25, 569252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='VideoConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('started', 'Started'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('provider_room', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_kind', models.CharField(default='twilio', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role__in': ['student', 'adult', 'visitor']}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
