# Generated by Django 5.1.7 on 2025-09-28 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_healthcard_expires_at_chatroom_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageReadStatus',
        ),
    ]
