# Generated by Django 5.1.7 on 2025-10-11 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_delete_messagereadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.doctorprofile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.facility')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'facility', 'day_of_week', 'start_time')},
            },
        ),
    ]
