# Generated by Django 5.1.7 on 2025-10-12 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.doctorprofile'),
        ),
    ]
