# Generated by Django 5.1.7 on 2025-10-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_shift_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcard',
            name='access_token',
            field=models.CharField(blank=True, editable=False, help_text='Secure token for accessing patient data via QR scan', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcard',
            name='scan_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='nfc_uid',
            field=models.CharField(blank=True, help_text='NFC chip UID if physical card exists', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='nhis_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='nhis_verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='nhis_verification_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='nhis_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcard',
            name='pin_hash',
            field=models.CharField(blank=True, help_text='Hashed PIN for verification', max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='healthcard',
            index=models.Index(fields=['access_token'], name='api_healthc_access__c7452e_idx'),
        ),
    ]
