# Generated by Django 5.1.7 on 2025-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_healthcard_access_token_healthcard_last_scanned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='scan_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
