# Generated by Django 5.1.7 on 2025-10-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_healthcard_scan_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcard',
            name='access_token',
            field=models.CharField(blank=True, help_text='Secure token for accessing patient data via QR scan', max_length=64, null=True, unique=True),
        ),
    ]
