# Generated by Django 5.1.7 on 2025-10-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_healthcard_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory')], max_length=20),
        ),
    ]
