# Generated by Django 5.1.7 on 2025-10-20 22:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_notification_metadata_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Time of the scan event.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the device that performed the scan.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser or device user agent string.', null=True)),
                ('success', models.BooleanField(default=True, help_text='Whether the scan was successful.')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure, if any (e.g., invalid PIN, expired card).', max_length=255, null=True)),
                ('card', models.ForeignKey(help_text='The health card that was scanned.', on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='api.healthcard')),
            ],
            options={
                'verbose_name': 'Scan Log',
                'verbose_name_plural': 'Scan Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['card', 'timestamp'], name='api_scanlog_card_id_209353_idx'), models.Index(fields=['ip_address'], name='api_scanlog_ip_addr_72ba8f_idx')],
            },
        ),
    ]
