# Generated by Django 5.1.7 on 2025-11-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_scanlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('facility_admin', 'Facility Admin'), ('student', 'Student'), ('adult', 'Adult'), ('visitor', 'Visitor'), ('doctor', 'Doctor'), ('lab_tech', 'Lab_Tech'), ('pharmacist', 'Pharmacist')], default='student', max_length=50),
        ),
    ]
