# Generated by Django 5.1.7 on 2025-11-12 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_prescription_consultation_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='valid_from',
            field=models.DateField(auto_now_add=True),
        ),
    ]
