# Generated by Django 5.1.7 on 2025-11-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_prescription_patient_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
