# Generated by Django 5.1.7 on 2025-11-12 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_otp_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('strength', models.CharField(blank=True, max_length=100, null=True)),
                ('form', models.CharField(blank=True, max_length=50, null=True)),
                ('is_generic', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-issued_at']},
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='drug_name',
        ),
        migrations.AddField(
            model_name='prescription',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='api.drug'),
        ),
        migrations.CreateModel(
            name='PharmacyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_stocks', to='api.drug')),
                ('pharmacy', models.ForeignKey(limit_choices_to={'facility_type': 'PHARMACY'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.facility')),
            ],
            options={
                'unique_together': {('pharmacy', 'drug')},
            },
        ),
    ]
