# Generated by Django 5.1.7 on 2025-11-12 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_drug_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinventory',
            name='pharmacy',
            field=models.ForeignKey(limit_choices_to={'facility_type': 'pharmacy'}, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='api.facility'),
        ),
    ]
