# Generated by Django 5.1.7 on 2025-11-13 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_pharmacyinventory_pharmacy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='patient_content_type',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient_object_id',
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Reason for prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes for pharmacist'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(default=5, limit_choices_to={'role__in': ['student', 'adult', 'visitor']}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-issued_at'], name='api_prescri_patient_84d3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status', '-issued_at'], name='api_prescri_status_c86e27_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['valid_until', 'status'], name='api_prescri_valid_u_912b62_idx'),
        ),
    ]
